export const mockData = {
  metrics: {
    totalRevenue: 45231.89,
    newCustomers: 2350,
    activeAccounts: 12234,
    growthRate: 5.7,
    activeUsers: 573,
  },
  revenueData: [
    { name: "Jan", total: 3000 },
    { name: "Feb", total: 3200 },
    { name: "Mar", total: 2800 },
    { name: "Apr", total: 3900 },
    { name: "May", total: 4200 },
    { name: "Jun", total: 3800 },
    { name: "Jul", total: 4500 },
    { name: "Aug", total: 4100 },
    { name: "Sep", total: 4800 },
    { name: "Oct", total: 5200 },
    { name: "Nov", total: 4900 },
    { name: "Dec", total: 5500 },
  ],
  recentSales: [
    {
      name: "Olivia Martin",
      email: "olivia.martin@email.com",
      amount: "+$1,999.00",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      name: "Jackson Lee",
      email: "jackson.lee@email.com",
      amount: "+$39.00",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      name: "Isabella Nguyen",
      email: "isabella.nguyen@email.com",
      amount: "+$299.00",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      name: "William Kim",
      email: "will@email.com",
      amount: "+$99.00",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      name: "Sofia Davis",
      email: "sofia.davis@email.com",
      amount: "+$39.00",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  ],
  topChannels: [
    { name: "Google Ads", visitors: 12500, percentage: 45, change: "+12.5%" },
    { name: "Facebook", visitors: 8200, percentage: 30, change: "+8.2%" },
    { name: "Direct", visitors: 4100, percentage: 15, change: "+2.1%" },
    { name: "Email", visitors: 2050, percentage: 7, change: "+5.3%" },
    { name: "Other", visitors: 820, percentage: 3, change: "-1.2%" },
  ],
  activityFeed: [
    {
      user: "John Doe",
      action: "created a new campaign",
      time: "2 minutes ago",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      user: "Sarah Wilson",
      action: "updated customer profile",
      time: "5 minutes ago",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      user: "Mike Johnson",
      action: "completed a purchase",
      time: "10 minutes ago",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      user: "Emily Brown",
      action: "left a product review",
      time: "15 minutes ago",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    {
      user: "David Lee",
      action: "subscribed to newsletter",
      time: "20 minutes ago",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  ],
  notifications: [
    {
      title: "New customer registered",
      description: "John Smith just created an account",
      time: "5 minutes ago",
    },
    {
      title: "Payment received",
      description: "Payment of $299.00 received from Acme Corp",
      time: "10 minutes ago",
    },
    {
      title: "Server maintenance scheduled",
      description: "Scheduled maintenance on Sunday at 2:00 AM",
      time: "1 hour ago",
    },
    {
      title: "New feature released",
      description: "Advanced analytics dashboard is now available",
      time: "2 hours ago",
    },
  ],
  trafficData: [
    { date: "2024-01-01", visitors: 1200 },
    { date: "2024-01-02", visitors: 1100 },
    { date: "2024-01-03", visitors: 1300 },
    { date: "2024-01-04", visitors: 1400 },
    { date: "2024-01-05", visitors: 1250 },
    { date: "2024-01-06", visitors: 1350 },
    { date: "2024-01-07", visitors: 1500 },
    { date: "2024-01-08", visitors: 1450 },
    { date: "2024-01-09", visitors: 1600 },
    { date: "2024-01-10", visitors: 1550 },
  ],
  trafficSources: [
    { name: "Direct", value: 35 },
    { name: "Google", value: 30 },
    { name: "Social Media", value: 20 },
    { name: "Email", value: 10 },
    { name: "Other", value: 5 },
  ],
  conversionFunnel: [
    { stage: "Visitors", users: 10000, percentage: 100 },
    { stage: "Sign-ups", users: 2500, percentage: 25 },
    { stage: "Trials", users: 1000, percentage: 10 },
    { stage: "Purchases", users: 250, percentage: 2.5 },
    { stage: "Renewals", users: 200, percentage: 2 },
  ],
  ageDistribution: [
    { name: "18-24", value: 15 },
    { name: "25-34", value: 35 },
    { name: "35-44", value: 25 },
    { name: "45-54", value: 15 },
    { name: "55+", value: 10 },
  ],
  deviceTypes: [
    { name: "Desktop", value: 45 },
    { name: "Mobile", value: 40 },
    { name: "Tablet", value: 15 },
  ],
}
